### ISSUE TITLE
allow changing number of rounds for risk adjustment

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/simulating-risk#42]

**Comment by rlskoeser** [comment]
@LaraBuchak I went to implement this and discovered that I'd already done it! I think I must have done it as part of implementing the risk attitude adjustment.  You can try it here: https://simrisk.pulcloud.io/hawkdove-variable

The parameter is currently labeled "Adjustment frequency (# rounds)" and allows a range from 1 to 30 (default is 10). Do you want any changes to the label or that range? Is there anything else I need to do with this?

**Comment by LaraBuchak** [comment]
This looks great, thanks!

From: Rebecca Sutton Koeser ***@***.***>
Date: Tuesday, November 7, 2023 at 3:44 PM
To: Princeton-CDH/simulating-risk ***@***.***>
Cc: Lara M. Buchak ***@***.***>, Mention ***@***.***>
Subject: Re: [Princeton-CDH/simulating-risk] allow changing number of rounds for risk adjustment (Issue #42)

@LaraBuchak<https://github.com/LaraBuchak> I went to implement this and discovered that I'd already done it! I think I must have done it as part of implementing the risk attitude adjustment. You can try it here: https://simrisk.pulcloud.io/hawkdove-variable

The parameter is currently labeled "Adjustment frequency (# rounds)" and allows a range from 1 to 30 (default is 10). Do you want any changes to the label or that range? Is there anything else I need to do with this?
