### ISSUE TITLE
hawk/dove: add and visualize agent payoffs

### ISSUE THREAD

**Issue by jerielizabeth** [Princeton-CDH/simulating-risk#48]
[ADDED 11/22]

This idea is fairly straightforward for simulations 1 [single risk-attitude] and 2 [multiple unchanging risk-attitudes]. Could be good to include mean, minimum, and maximum total payoff by risk-attitude: calculate total payoff for each *agent*, and then, for each risk attitude, take the mean, min, and max of the payoffs for agents who have that risk attitude. [Importantly: we don’t want to take, for example, the minimum payoff some agent gets on a round–we want to take these statistics for each agent’s total.] It will be boring for simulation 1: since we very quickly get a blinking state, everyone has the same average payoff. For simulation 2, we know that the risk-seekers play H more and the risk-avoiders play D more; we want to know whether the risk-seekers are doing better, and are all of them doing better, or are there some “big winners” and other “big losers” etc.

For simulation 3, there’s a difficulty in breaking it up by risk attitude, since the risk attitudes are changing. I think what we’re interested in is which end-states have the highest payoffs for the agents in them (for example, are end-state populations with more risk-avoidant agents better off, sort of vindicating Simon’s idea?). So maybe we want to calculate, for each simulation, (1) the average payoff for all agents; and (2) the average payoff for agents in each “band” (0-2, 3-5, 6-8).

## dev notes

- [x] implement a wealth payoff chart for hawk/dove multi; create a box plot of total wealth for each risk attitude
- [x] re-order charts on hawk/dove multi interface - move rolling % hawk last; add new wealth payoff chart after the % hawk by risk attitude

**Comment by rlskoeser** [comment]
implemented in #69
