### ISSUE TITLE
 INTRODUCE RANDOMNESS  [ROBUSTNESS]

### ISSUE THREAD

**Issue by jerielizabeth** [Princeton-CDH/simulating-risk#53]
For example: each agent has a 0.01 chance of just playing DOVE and a 0.01 chance of just playing HAWK rather than using our standard procedure to determine what he plays.  (Or change these numbers, maybe make them higher?)

**Comment by rlskoeser** [comment]
duplicate of #45 ; will keep that one and add the robustness label
